import { Listing, PlatformSettings } from '../types/marketplace';

export const INITIAL_PLATFORM_SETTINGS: PlatformSettings = {
  defaultCommissionRate: 2.5,
  feeModel: 'add_to_customer',
  allowCategorySpecific: true,
  categoryRates: {
    'Tractors': 2.5,
    'Farm Vehicles': 2.5,
    'Harvesting Equipment': 3.0,
    'Agricultural Machinery': 2.5,
    'Tools & Equipment': 2.0,
    'Land': 2.5,
    'Storage': 2.5,
    'Irrigation Equipment': 2.0,
    'Farming Services': 3.0,
    'Other': 2.5,
  },
  allowOwnerSpecific: false,
  ownerRates: {},
  allowPromotional: false,
  payoutDelayDays: 3,
  gstRatePercent: 18,
  minPayoutAmountINR: 500,
  auditLogs: [
    {
      id: 'audit_init',
      adminEmail: 'admin@agrishare.in',
      oldRate: 3.0,
      newRate: 2.5,
      changedAt: '2026-08-01T10:00:00.000Z',
      reason: 'Standardized national farmer-first commission policy to 2.5%'
    }
  ]
};

export const SEED_LISTINGS: Listing[] = [
  {
    id: 'list_1',
    title: 'John Deere 5050D (50 HP) Heavy Tillage Tractor',
    category: 'Tractors',
    subcategory: '50 HP Utility',
    description: 'Fuel-efficient 50 HP power steering tractor with dual clutch, oil immersed disc brakes and high backup torque. Regularly serviced at authorized dealer. Comes with heavy drawbar and rear PTO ready.',
    pricePerDay: 2800,
    pricePerHour: 400,
    pricePerWeek: 16500,
    pricePerMonth: 58000,
    pricingUnit: 'day',
    securityDeposit: 3000,
    location: 'Springfield Farm, 4 km from APMC Market',
    city: 'Nashik',
    state: 'Maharashtra',
    pincode: '422003',
    distanceKm: 4.2,
    images: [
      'https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=1200&q=80'
    ],
    coverImage: 'https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?auto=format&fit=crop&w=1200&q=80',
    condition: 'Excellent',
    deliveryAvailable: true,
    deliveryFee: 450,
    pickupAvailable: true,
    operatorAvailable: true,
    maintenanceIncluded: true,
    vehicleSpecs: {
      hp: 50,
      brand: 'John Deere',
      model: '5050D 2WD',
      year: 2024,
      capacity: '1600 kg hitch lifting capacity',
      fuelType: 'Diesel',
      driveType: '2WD',
      operatorAvailable: true,
      attachmentAvailability: 'Includes MB Plough & Cultivator pins'
    },
    ownerId: 'owner_robert',
    ownerName: 'Robert K. (Green Valley Farms)',
    ownerEmail: 'robert.k@springfieldfarm.com',
    ownerPhone: '+91 98230 44120',
    ownerRating: 4.9,
    ownerReviewCount: 28,
    isOwnerVerified: true,
    isListingVerified: true,
    status: 'active',
    minRentalDuration: 1,
    maxRentalDuration: 30,
    blockedDates: ['2026-10-15', '2026-10-16'],
    createdAt: '2026-08-10T08:00:00.000Z',
    updatedAt: '2026-09-20T12:00:00.000Z'
  },
  {
    id: 'list_2',
    title: '5-Acre Fertile Organic Farmland with High-Yield Borewell',
    category: 'Land',
    subcategory: 'Agricultural Farmland',
    description: 'Rich fertile deep black cotton soil with high organic matter, ideal for seasonal vegetables, onions, soybeans or cotton. Equipped with solar-powered 7.5 HP borewell running 24x7, full perimeter chain-link wire fencing, 20-ft motorable all-weather road access, and a small dry storehouse.',
    pricePerDay: 750,
    pricePerMonth: 18000,
    pricingUnit: 'acre/month',
    securityDeposit: 10000,
    location: 'Dindori Taluka, Near Highway Bypass',
    city: 'Nashik',
    state: 'Maharashtra',
    pincode: '422202',
    distanceKm: 12.5,
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=1200&q=80'
    ],
    coverImage: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
    condition: 'Brand New',
    deliveryAvailable: false,
    deliveryFee: 0,
    pickupAvailable: true,
    operatorAvailable: false,
    maintenanceIncluded: true,
    landSpecs: {
      area: 5,
      areaUnit: 'acre',
      soilType: 'Deep Black Cotton Soil (Regur)',
      waterAvailability: 'Borewell',
      electricity: true,
      roadAccess: true,
      fencing: true,
      storageOnSite: true,
      cropSuitability: ['Onions', 'Soybean', 'Wheat', 'Vegetables', 'Cotton', 'Grapes']
    },
    ownerId: 'owner_patel',
    ownerName: 'Vikas Patel',
    ownerEmail: 'vikas.patel@agrishare.in',
    ownerPhone: '+91 94222 89012',
    ownerRating: 4.8,
    ownerReviewCount: 14,
    isOwnerVerified: true,
    isListingVerified: true,
    status: 'active',
    minRentalDuration: 30,
    maxRentalDuration: 365,
    blockedDates: [],
    createdAt: '2026-08-15T09:30:00.000Z',
    updatedAt: '2026-09-22T14:15:00.000Z'
  },
  {
    id: 'list_3',
    title: 'Claas Crop Tiger Combine Harvester (Wheeled) with Operator',
    category: 'Harvesting Equipment',
    subcategory: 'Paddy & Grain Harvester',
    description: 'High-speed multi-crop combine harvester equipped with specialized grain cleaning mechanism, high threshing cylinder diameter and adjustable reel speed. Operates with certified experienced driver for minimal grain loss during wheat, paddy and mustard harvesting.',
    pricePerDay: 14500,
    pricePerHour: 1800,
    pricingUnit: 'day',
    securityDeposit: 5000,
    location: 'GT Road Agricultural Belt, 6 km from Toll Plaza',
    city: 'Karnal',
    state: 'Haryana',
    pincode: '132001',
    distanceKm: 8.7,
    images: [
      'https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1589923188651-268a9765e432?auto=format&fit=crop&w=1200&q=80'
    ],
    coverImage: 'https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=1200&q=80',
    condition: 'Excellent',
    deliveryAvailable: true,
    deliveryFee: 1200,
    pickupAvailable: false,
    operatorAvailable: true,
    maintenanceIncluded: true,
    vehicleSpecs: {
      hp: 75,
      brand: 'Claas',
      model: 'Crop Tiger 40',
      year: 2023,
      capacity: '2.5 - 3 acres per hour harvesting capacity',
      fuelType: 'Diesel',
      driveType: '2WD',
      operatorAvailable: true,
      attachmentAvailability: 'Includes Grain Header & Cutter Bar'
    },
    ownerId: 'owner_gurpreet',
    ownerName: 'Gurpreet Singh',
    ownerEmail: 'gurpreet.karnal@agrishare.in',
    ownerPhone: '+91 98120 55431',
    ownerRating: 4.9,
    ownerReviewCount: 42,
    isOwnerVerified: true,
    isListingVerified: true,
    status: 'active',
    minRentalDuration: 1,
    maxRentalDuration: 14,
    blockedDates: ['2026-10-05', '2026-10-06', '2026-10-07'],
    createdAt: '2026-08-05T11:00:00.000Z',
    updatedAt: '2026-09-25T16:00:00.000Z'
  },
  {
    id: 'list_4',
    title: 'Shaktiman 7-Feet Heavy Duty Multi-Speed Rotavator',
    category: 'Agricultural Machinery',
    subcategory: 'Soil Preparation',
    description: 'Heavy duty rotary tiller designed for tough Indian soil conditions. Equipped with boron steel curved blades (L-type), boron steel gear transmission, and adjustable trailing board for fine tilth seedbed preparation.',
    pricePerDay: 1600,
    pricePerWeek: 9500,
    pricingUnit: 'day',
    securityDeposit: 2000,
    location: 'Sector 5 Industrial & Farm Hub',
    city: 'Indore',
    state: 'Madhya Pradesh',
    pincode: '452010',
    distanceKm: 6.1,
    images: [
      'https://images.unsplash.com/photo-1589923188651-268a9765e432?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1534073133331-c4b62a557083?auto=format&fit=crop&w=1200&q=80'
    ],
    coverImage: 'https://images.unsplash.com/photo-1589923188651-268a9765e432?auto=format&fit=crop&w=1200&q=80',
    condition: 'Excellent',
    deliveryAvailable: true,
    deliveryFee: 350,
    pickupAvailable: true,
    operatorAvailable: false,
    maintenanceIncluded: true,
    vehicleSpecs: {
      hp: 45,
      brand: 'Shaktiman',
      model: 'Regular Plus 210',
      year: 2024,
      capacity: '48 blades / 7 ft width',
      fuelType: 'Manual',
      attachmentAvailability: 'Standard 3-point CAT-II linkage'
    },
    ownerId: 'owner_robert',
    ownerName: 'Robert K. (Green Valley Farms)',
    ownerEmail: 'robert.k@springfieldfarm.com',
    ownerPhone: '+91 98230 44120',
    ownerRating: 4.9,
    ownerReviewCount: 28,
    isOwnerVerified: true,
    isListingVerified: true,
    status: 'active',
    minRentalDuration: 1,
    maxRentalDuration: 20,
    blockedDates: [],
    createdAt: '2026-08-12T10:00:00.000Z',
    updatedAt: '2026-09-24T11:00:00.000Z'
  },
  {
    id: 'list_5',
    title: 'Kirloskar 7.5 HP High-Head Solar Agricultural Pump Set',
    category: 'Irrigation Equipment',
    subcategory: 'Solar Pumps',
    description: 'Complete high-efficiency submersible solar pump with 10 high-output solar panels and variable frequency drive controller. Provides uninterrupted water flow of up to 450 liters per minute even in hazy morning sunlight.',
    pricePerDay: 1200,
    pricePerWeek: 7000,
    pricePerMonth: 22000,
    pricingUnit: 'day',
    securityDeposit: 3500,
    location: 'Near Old River Bridge, Taluka Road',
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '411038',
    distanceKm: 14.0,
    images: [
      'https://images.unsplash.com/photo-1560493676-04071c5f467b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=1200&q=80'
    ],
    coverImage: 'https://images.unsplash.com/photo-1560493676-04071c5f467b?auto=format&fit=crop&w=1200&q=80',
    condition: 'Excellent',
    deliveryAvailable: true,
    deliveryFee: 500,
    pickupAvailable: true,
    operatorAvailable: false,
    maintenanceIncluded: true,
    vehicleSpecs: {
      hp: 7.5,
      brand: 'Kirloskar',
      model: 'Jalraaj Solar 750',
      year: 2024,
      capacity: '450 LPM delivery head up to 60 meters',
      fuelType: 'Electric'
    },
    ownerId: 'owner_suresh',
    ownerName: 'Suresh Deshmukh',
    ownerEmail: 'suresh.d@agrishare.in',
    ownerPhone: '+91 97654 32190',
    ownerRating: 4.7,
    ownerReviewCount: 19,
    isOwnerVerified: true,
    isListingVerified: true,
    status: 'active',
    minRentalDuration: 2,
    maxRentalDuration: 60,
    blockedDates: [],
    createdAt: '2026-08-20T14:00:00.000Z',
    updatedAt: '2026-09-26T09:00:00.000Z'
  },
  {
    id: 'list_6',
    title: 'Mahindra Bolero Maxi Truck Plus (Farm Transport Vehicle)',
    category: 'Farm Vehicles',
    subcategory: 'Light Commercial Vehicle',
    description: 'High payload 1.2-tonne rugged pickup vehicle engineered for rural and farm roads. Large 40.9 sq. ft cargo deck for hauling grain sacks, harvested fruits, fertilizer bags or small equipment.',
    pricePerDay: 2200,
    pricePerWeek: 13000,
    pricingUnit: 'day',
    securityDeposit: 2500,
    location: 'APMC Market Yard Gate 2',
    city: 'Baramati',
    state: 'Maharashtra',
    pincode: '413102',
    distanceKm: 5.5,
    images: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?auto=format&fit=crop&w=1200&q=80'
    ],
    coverImage: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80',
    condition: 'Good',
    deliveryAvailable: true,
    deliveryFee: 300,
    pickupAvailable: true,
    operatorAvailable: true,
    maintenanceIncluded: true,
    vehicleSpecs: {
      hp: 65,
      brand: 'Mahindra',
      model: 'Bolero Maxi Truck Plus',
      year: 2023,
      capacity: '1200 kg certified payload',
      fuelType: 'Diesel',
      driveType: '2WD',
      operatorAvailable: true
    },
    ownerId: 'owner_ramesh_transport',
    ownerName: 'Kailash Jadhav',
    ownerEmail: 'kailash.j@agrishare.in',
    ownerPhone: '+91 99210 77341',
    ownerRating: 4.8,
    ownerReviewCount: 31,
    isOwnerVerified: true,
    isListingVerified: true,
    status: 'active',
    minRentalDuration: 1,
    maxRentalDuration: 15,
    blockedDates: [],
    createdAt: '2026-08-18T10:00:00.000Z',
    updatedAt: '2026-09-21T11:00:00.000Z'
  },
  {
    id: 'list_7',
    title: 'Precision AgriDrone Crop Health & Pesticide Spraying Service',
    category: 'Farming Services',
    subcategory: 'Drone Spraying with DGCA Certified Pilot',
    description: 'Precision spraying of micronutrients, liquid fertilizers and pest control solutions with ultra-fine droplet spectrum. Covers up to 25 acres per day with 90% water saving and zero field soil compaction.',
    pricePerDay: 4800,
    pricePerHour: 750,
    pricingUnit: 'day',
    securityDeposit: 1500,
    location: 'Agritech Innovation Cluster, MIDC',
    city: 'Aurangabad',
    state: 'Maharashtra',
    pincode: '431001',
    distanceKm: 9.3,
    images: [
      'https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1594771804886-a933bb2d609b?auto=format&fit=crop&w=1200&q=80'
    ],
    coverImage: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=1200&q=80',
    condition: 'Brand New',
    deliveryAvailable: true,
    deliveryFee: 250,
    pickupAvailable: false,
    operatorAvailable: true,
    maintenanceIncluded: true,
    ownerId: 'owner_patel',
    ownerName: 'Vikas Patel',
    ownerEmail: 'vikas.patel@agrishare.in',
    ownerPhone: '+91 94222 89012',
    ownerRating: 4.8,
    ownerReviewCount: 14,
    isOwnerVerified: true,
    isListingVerified: true,
    status: 'active',
    minRentalDuration: 1,
    maxRentalDuration: 7,
    blockedDates: [],
    createdAt: '2026-08-25T11:00:00.000Z',
    updatedAt: '2026-09-27T17:00:00.000Z'
  },
  {
    id: 'list_8',
    title: 'Solar Powered 10-Tonne Micro Cold Storage for Fresh Produce',
    category: 'Storage',
    subcategory: 'Cold Storage Room',
    description: 'Eco-friendly walk-in cold room maintaining 4°C to 12°C with precision humidity control for freshly picked vegetables, flowers and fruits to prevent distress selling at mandis.',
    pricePerDay: 1800,
    pricePerMonth: 38000,
    pricingUnit: 'day',
    securityDeposit: 4000,
    location: 'Khadki Rural Hub, Near Farm Gate',
    city: 'Anand',
    state: 'Gujarat',
    pincode: '388001',
    distanceKm: 11.2,
    images: [
      'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1534073133331-c4b62a557083?auto=format&fit=crop&w=1200&q=80'
    ],
    coverImage: 'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?auto=format&fit=crop&w=1200&q=80',
    condition: 'Excellent',
    deliveryAvailable: false,
    deliveryFee: 0,
    pickupAvailable: true,
    operatorAvailable: false,
    maintenanceIncluded: true,
    ownerId: 'owner_anand_cold',
    ownerName: 'Manish Rawal',
    ownerEmail: 'manish.r@agrishare.in',
    ownerPhone: '+91 98980 12345',
    ownerRating: 4.9,
    ownerReviewCount: 16,
    isOwnerVerified: true,
    isListingVerified: true,
    status: 'active',
    minRentalDuration: 3,
    maxRentalDuration: 90,
    blockedDates: [],
    createdAt: '2026-08-22T08:00:00.000Z',
    updatedAt: '2026-09-24T14:00:00.000Z'
  }
];
